#################################
### DO NOT EDIT THIS FILE !!! ###
#################################
"""
Do not edit this file; it is used
by the autograder.  However, you
are welcome and encouraged to
write your own testing code in 
the main file or in your own file.
"""

from scrabble import BestBingoLetters

######  Problem #6 #########################

def wordkey(word):
    l = list(word)
    l.sort()
    return "".join(l)


def test_P6():
    assert list(map(wordkey, BestBingoLetters())) == ['aeginrst']
    
