#################################
### DO NOT EDIT THIS FILE !!! ###
#################################
"""
Do not edit this file; it is used
by the autograder.  However, you
are welcome and encouraged to
write your own testing code in 
the main file or in your own file.
"""

from scrabble import CanBeMadeFrom

######  Problem #3 #########################

def test_P3_simple_true_same_length():
    assert CanBeMadeFrom("red","edr") == True

def test_P3_simple_true_different_length():
    assert CanBeMadeFrom("red","tedr") == True

def test_P3_simple_false():
    assert CanBeMadeFrom("red", "rem") == False

def test_P3_simple_false_differnt_length():
    assert CanBeMadeFrom("red", "remit") == False

def test_P3_true_with_repeats():
    assert CanBeMadeFrom("stopped","oossttppeeddff") == True

def test_P3_false_with_repeats():
    assert CanBeMadeFrom("mitt", "time") == False

def test_P3_false_with_repeats():
    assert CanBeMadeFrom("mitt", "tim") == False
