import pytest
from lists import *
print("Stack:")
s=Stack()
s.push(1)
s.push(2)
s.push(3)
print(s.__repr__())
print("Stack pop:")
print(s.pop())
print(s.pop())
print(s.pop())
print("Stack is empty:")
print(s.isEmpty())
print("")

print("Queue:")
x=Queue()
x.enqueue(1)
x.enqueue(2)
x.enqueue(3)
print(x.__repr__())
print("Queue dequeue:")
print(x.dequeue())
print(x.dequeue())
print(x.dequeue())
print("Queue is empty:")
print(x.isEmpty())
print("")

print("linked list:")
l=Linked_List()
print("is the LL empty? " + str(l.isEmpty()))
l.add(1)
l.add(2)
l.add(3)
l.add(4)
l.add(5)
l.add(6)
print("linked list contents:")
print(l.__repr__())
print("")
print("removed 2: " + str(l.remove(2)))
print(l.__repr__())
print("")
print("search: 1 " + str(l.search(1)))
print("search: 2 " + str(l.search(2)))
print("")
print("is the LL empty? " + str(l.isEmpty()))
print("size: " + str(l.size()))
l.append(7)
print(l.__repr__())
print("")
print("find the index of 7: "+str(l.index(7)))
print("find the index of 2: "+str(l.index(2)))
print("")
print("insert 8 at index 3")
l.insert(3,8)
print(l.__repr__())
print("")
print(l.pop())
print(l.__repr__())
print("")
print(l.popfrom(2))
print(l.__repr__())
print("")
