#################################
### DO NOT EDIT THIS FILE !!! ###
#################################
"""
Do not edit this file; it is used
by the autograder.  However, you
are welcome and encouraged to
write your own testing code in 
the main file or in your own file.
"""
import pytest
from lists import Queue

######  Problem #2 #########################

def test_P2_create_empty_queue():
    q = Queue()
    assert q.isEmpty() == True

def test_P2_create_nonempty_queue():
    q = Queue()
    q.enqueue("test")
    assert q.isEmpty() == False

def test_P2_one_element_queue():
    q = Queue()
    q.enqueue("test")
    assert q.dequeue() == "test"

def test_P2_dequeue_removes_element():
    q = Queue()
    q.enqueue("test")
    q.dequeue()
    assert q.isEmpty() == True

def test_P2_dequeue_from_empty():
    q = Queue()
    with pytest.raises(Exception):
        q.dequeue()

def test_P2_size():
    q = Queue()
    q.enqueue(1)
    q.enqueue(2)
    q.enqueue(3)
    q.enqueue(4)
    q.dequeue()
    assert q.size() == 3

def test_P2_dequeue_from_correct_end():
    q = Queue()
    q.enqueue(1)
    q.enqueue(2)
    q.enqueue(3)
    assert q.dequeue() == 1





