#################################
### DO NOT EDIT THIS FILE !!! ###
#################################
"""
Do not edit this file; it is used
by the autograder.  However, you
are welcome and encouraged to
write your own testing code in 
the main file or in your own file.
"""

from scrabble import SpellingBee

######  Problem #5 #########################

def test_P5():
    l = SpellingBee("p","rimlat")
    l.sort()
    assert l == ['apart', 'appal', 'appall', 'apparat', 'arapaima', 'armpit', 'atrip', 'impair', 'impala', 'impart', 'lapilli', 'milpa', 'palatal', 'palatial', 'pallia', 'pallial', 'palmar', 'palpal', 'palpi', 'pampa', 'papal', 'papilla', 'papillar', 'pappi', 'parral', 'partial', 'partita', 'patamar', 'pattamar', 'pilar', 'pillar', 'pipal', 'pipit', 'pitapat', 'plait', 'praam', 'priapi', 'prill', 'prima', 'primal', 'primatal', 'primi', 'primp', 'rampart', 'rattrap', 'riprap', 'tampala', 'tapir', 'tilapia', 'tramp', 'trapt', 'tripart']
